# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  CGO_ENABLED: 0
  

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test
        run: go test -v ./...

      - name: Build Linux
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -v -o pms_linux ./cmd

      - name: Build MacOS ARM
        env:
          GOOS: darwin
          GOARCH: arm64
        run: go build -v -o pms_macos_arm ./cmd

      - name: Build MacOS AMD
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -v -o pms_macos_amd ./cmd

      - name: Build Windows 64
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -v -o pms_windows_64 ./cmd

    
